Add database support.

diff --git a/ddccontrol/configure b/ddccontrol/configure
--- a/ddccontrol/configure
+++ b/ddccontrol/configure
@@ -310,7 +310,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot RANLIB ac_ct_RANLIB CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP EGREP PKG_CONFIG GNOME_LDFLAGS GNOME_CFLAGS GDDCCONTROL LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot RANLIB ac_ct_RANLIB CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP EGREP XML2_CONFIG PKG_CONFIG GNOME_LDFLAGS GNOME_CFLAGS GDDCCONTROL LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -3648,8 +3648,8 @@ if test `eval echo '${'$as_ac_Header'}'` = yes; then
 _ACEOF
 
 else
-  { { echo "$as_me:$LINENO: error: Important header not found, please install them." >&5
-echo "$as_me: error: Important header not found, please install them." >&2;}
+  { { echo "$as_me:$LINENO: error: Important header not found, please install it." >&5
+echo "$as_me: error: Important header not found, please install it." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -3810,9 +3810,70 @@ fi
 done
 
 
-CFLAGS="$CFLAGS -Wall"
+# libxml2 check
 
-# Extract the first word of "pkg-config", so it can be a program name with args.
+# Extract the first word of "xml2-config", so it can be a program name with args.
+set dummy xml2-config; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_XML2_CONFIG+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $XML2_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_XML2_CONFIG="$XML2_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_XML2_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  test -z "$ac_cv_path_XML2_CONFIG" && ac_cv_path_XML2_CONFIG="no"
+  ;;
+esac
+fi
+XML2_CONFIG=$ac_cv_path_XML2_CONFIG
+
+if test -n "$XML2_CONFIG"; then
+  echo "$as_me:$LINENO: result: $XML2_CONFIG" >&5
+echo "${ECHO_T}$XML2_CONFIG" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+if test "x$XML2_CONFIG" = "xno" ; then
+   { { echo "$as_me:$LINENO: error: xml2-config not found" >&5
+echo "$as_me: error: xml2-config not found" >&2;}
+   { (exit please install libxml2); exit please install libxml2; }; }
+fi
+
+CFLAGS="$CFLAGS -Wall `xml2-config --cflags`"
+LDFLAGS="$LDFLAGS `xml2-config --libs`"
+
+# Gnome check
+
+# Check whether --enable-gnome or --disable-gnome was given.
+if test "${enable_gnome+set}" = set; then
+  enableval="$enable_gnome"
+  if test x$enableval = xyes; then
+    support_gnome=yes
+  fi
+fi;
+
+GDDCCONTROL=
+if test x$support_gnome = xyes; then
+   # Extract the first word of "pkg-config", so it can be a program name with args.
 set dummy pkg-config; ac_word=$2
 echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
@@ -3852,24 +3913,12 @@ else
 echo "${ECHO_T}no" >&6
 fi
 
-if test "x$PKG_CONFIG" = "xno" ; then
-	{ { echo "$as_me:$LINENO: error: pkg-config not found please install pkg-config" >&5
-echo "$as_me: error: pkg-config not found please install pkg-config" >&2;}
-   { (exit 1); exit 1; }; }
-fi
+   if test "x$PKG_CONFIG" = "xno" ; then
+      { { echo "$as_me:$LINENO: error: pkg-config not found" >&5
+echo "$as_me: error: pkg-config not found" >&2;}
+   { (exit please install pkg-config); exit please install pkg-config; }; }
+   fi
 
-# Gnome check
-
-# Check whether --enable-gnome or --disable-gnome was given.
-if test "${enable_gnome+set}" = set; then
-  enableval="$enable_gnome"
-  if test x$enableval = xyes; then
-    support_gnome=yes
-  fi
-fi;
-
-GDDCCONTROL=
-if test x$support_gnome = xyes; then
    echo -n "checking for gtk+-2.0... "
    if pkg-config --exists gtk+-2.0 ; then
       GNOME_LDFLAGS="`pkg-config --libs gtk+-2.0`"
@@ -4568,6 +4617,7 @@ s,@am__fastdepCC_TRUE@,$am__fastdepCC_TRUE,;t t
 s,@am__fastdepCC_FALSE@,$am__fastdepCC_FALSE,;t t
 s,@CPP@,$CPP,;t t
 s,@EGREP@,$EGREP,;t t
+s,@XML2_CONFIG@,$XML2_CONFIG,;t t
 s,@PKG_CONFIG@,$PKG_CONFIG,;t t
 s,@GNOME_LDFLAGS@,$GNOME_LDFLAGS,;t t
 s,@GNOME_CFLAGS@,$GNOME_CFLAGS,;t t
